In [1]:
# numpy version
import numpy as np
print(np.__version__)

2.4.4


In [2]:
# 2. Convert List to 1D Array
# Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
# Expected Output:
# Original List: [12.23, 13.32, 100, 36.32]
# One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

list_1=[12.23, 13.32, 100, 36.32]
arr_1=np.array(list_1)
print(arr_1)

[ 12.23  13.32 100.    36.32]


In [4]:
# Create 3x3 Matrix (2?10)

# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

# Expected Output:

# [[ 2 3 4]
# [ 5 6 7]
# [ 8 9 10]]

a=np.array([[2,3,4],
           [5,6,7],
           [8,9,10]])
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
# 4. Null Vector (10) & Update Sixth Value
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11. Scripting Languages
# [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# Update sixth value to 11
# [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

a=np.zeros(10)
a[6]=1
a

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [17]:
a=np.arange(12,20)
a

array([12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12])

In [27]:
# 7. Convert Array to Float Type
#Write a NumPy program to convert an array to a floating type.
# Sample output:
# Original array
# [1, 2, 3, 4]
# Array converted to a float type:
# [ 1. 2. 3. 4.]

a=np.array([1,2,3,4])
a=np.float32(a)
a



array([1., 2., 3., 4.], dtype=float32)

In [29]:
# 8. 2D Array (Border 1, Inside 0)

# Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

# Expected Output:

# Original array:
# [[ 1. 1. 1. 1. 1.]
# ...................
# [ 1. 1. 1. 1. 1.]]

# 1 on the border and 0 inside in the array
# [[ 1. 1. 1. 1. 1.]
# ...................
# [ 1. 1. 1. 1. 1.]]
a=np.ones((5,5))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# 9. Add Border to Array (0s)

# Write a NumPy program to add a border (filled with 0's) around an existing array.

# Expected Output:

# Original array:
# [[ 1. 1. 1.]
# [ 1. 1. 1.]
# [ 1. 1. 1.]]

# 1 on the border and 0 inside in the array
# [[ 0. 0. 0. 0. 0.]
# ...........
# [ 0. 0. 0. 0. 0.]]

a=np.zeros((10,10))
a[1:-1,1:-1]=1
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
# 10. 8x8 Checkerboard Pattern
# Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.Scripting Languages
# Checkerboard pattern:
# [[0 1 0 1 0 1 0 1]
# ..........
# [0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]]

a=np.ones((10,10))
a[::2,::2]=0
a

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
# 11. List/Tuple to Arrays

# Write a NumPy program to convert a list and tuple into arrays.

# List to array:
# [1 2 3 4 5 6 7 8]

# Tuple to array:
# [[8 4 6]
# [1 2 3]]

tuple_1=(1,1,1,0)
a=np.array(tuple_1)
a

array([1, 1, 1, 0])

In [45]:
# 12. Append Values to Array
# Write a NumPy program to append values to the end of an array.
# Expected Output:
# Original array:
# [10, 20, 30]
# After append values to the end of the array:
# [10 20 30 40 50 60 70 80 90]

# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a Python list
x = [10, 20, 30]

# Printing a message indicating the original array
print("Original array:")

# Printing the original array
print(x)

# Appending values to the end of the array using np.append() and assigning the result back to 'x'
x = np.append(x, [[40, 50, 60], [70, 80, 90]])

# Printing a message indicating the array after appending values
print("After append values to the end of the array:")

# Printing the array after appending values
print(x)


Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [47]:
x=[1,2,3]
x=np.append(x,[10,10,10])
x

array([ 1,  2,  3, 10, 10, 10])

In [50]:
# 13. Create Empty and Full Array
# Write a NumPy program to create an empty and full array.
# Expected Output:
# [ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
# [ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
# [ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]
# [[6 6 6]
# [6 6 6]
# [6 6 6]]

x=np.empty((3,3))
x
x2=np.full((3,3),100)
x2

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [1]:
import numpy as np
# 4. Celsius to Fahrenheit Conversion
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.
# Sample Array [0, 12, 45.21, 34, 99.91]
# [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]
# Expected Output:
# Values in Fahrenheit degrees:
# [ 0. 12. 45.21 34. 99.91 32. ]
# Values in Centigrade degrees:
# [-17.78 -11.11 7.34 1.11 37.73 0. ]
# Values in Centigrade degrees:
# [-17.78 -11.11 7.34 1.11 37.73 0. ]
# Values in Fahrenheit degrees:
# [-0. 12. 45.21 34. 99.91 32. ]

temp=np.array([0, 12, 45.21, 34, 99.91])
faren=temp*1.8+32
print(faren)

[ 32.     53.6   113.378  93.2   211.838]


In [9]:
'''15. Real/Imaginary Parts of Complex Array

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

Expected Output:

Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

Real part of the array:
[ 1. 0.70710678]

Imaginary part of the array:
[ 0. 0.70710678]'''
x=np.array([1+2.j,2-3.j])
x2=x.real
x3=x.imag

x2, x3

(array([1., 2.]), array([ 2., -3.]))

In [11]:
#16. Array Elements Count & Memory Usage
#Write a NumPy program to find the number of elements in an array. It also finds the length of one array element in bytes and the total bytes consumed by the elements.Scripting Languages
#Expected Output:
#Size of the array: 3
#Length of one array element in bytes: 8
#Total bytes consumed by the elements of the array: 24

x=np.arange(0,25)
x.size

25

In [15]:
#17. 1D Array Element Check in Another Array

#Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

#Expected Output:

#Array1: [ 0 10 20 40 60]
#Array2: [0, 40]

#Compare each element of array1 and array2
#[ True False False True False]
x=np.array([0,10,20,40,60])
y=np.array([0,40])
np.isin(x,y)

array([ True, False, False,  True, False])

In [16]:
# 18. Common Values in Two Arrays
# Write a NumPy program to find common values between two arrays.
# Expected Output:
# Array1: [ 0 10 20 40 60]
# Array2: [10, 30, 40]
# Common values between two arrays:
# [10 40]

np.intersect1d(x,y)

array([ 0, 40])

In [20]:
# 19. Unique Elements of Array
# Write a NumPy program to get the unique elements of an array.
# Expected Output:
# Original array:
# [10 10 20 20 30 30]
# Unique elements of the above array:
# [10 20 30]
# Original array:
# [[1 1]
# [2 3]]
# Unique elements of the above array:
# [1 2 3]
x=np.array([10,10,20,20,30,30])
y=np.array([
    [10,10],
           [20,20],
           [30,30],
           ])
np.unique(y)


array([10, 20, 30])

In [21]:
# 20. Set Difference of Arrays

# Write a NumPy program to find the set difference between two arrays. 
#The set difference will return sorted, distinct values in array1 that are not in array2.

# Expected Output:

# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70, 90]

# Set difference between two arrays:
# [ 0 20 60 80]
x=np.array([0,10,20,40,60,80])
y=np.array([10,30,40,50,70,90])
np.setdiff1d(x,y)

array([ 0, 20, 60, 80])

In [22]:
# 21. Set Exclusive-Or of Arrays

# Write a NumPy program to find the set exclusive-or of two arrays.
#Set exclusive-or will return sorted, distinct values in only one (not both) of the input arrays.

# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70]

# Unique values that are in only one (not both) of the input arrays:
# [ 0 20 30 50 60 70 80]
np.setxor1d(x,y)


array([ 0, 20, 30, 50, 60, 70, 80, 90])

In [23]:
# 22. Union of Two Arrays

# Write a NumPy program to find the union of two arrays. Union will return a unique, sorted array of values in each of the two input arrays. Scripting Languages

# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70]

# Unique sorted array of values that are in either of the two input arrays:
# [ 0 10 20 30 40 50 60 70 80]

x=np.array([1,2,3,4])
y=np.array([4,5,6,7])
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
# 23. Test All Elements are True
# Write a NumPy program to test whether all elements in an array evaluate to True.
# Note: 0 evaluates to False in NumPy.

x=np.array([True,True,True])
np.all(x)

np.True_

In [35]:
# 24. Test Any Element is True

# Write a NumPy program to test whether any array element along a given axis evaluates to True.

# Note: 0 evaluates to False in NumPy.
x=np.array([
    [False,False],
    [False,False]
])
np.any(x)

np.False_

In [37]:
# 25. Repeat Array Entirely
# Write a NumPy program to construct an array by repeating.
# Sample array: [1, 2, 3, 4]
# Expected Output:
# Original array
# [1, 2, 3, 4]
# Repeating 2 times
# [1 2 3 4 1 2 3 4]
# Repeating 3 times
# [1 2 3 4 1 2 3 4 1 2 3 4]

x=np.arange(0,5)
np.tile(x,2)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [38]:
# 26. Repeat Each Array Element
# Write a NumPy program to repeat array elements.
# Expected Output:
# [3 3 3 3]
# [1 1 2 2 3 3 4 4]

x=np.arange(5,10)
np.repeat(x,4)

array([5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9])

In [48]:
# 27. Indices of Max/Min Along Axis
# Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.
# Original array: [1 2 3 4 5 6]
# Maximum Values: 5
# Minimum Values: 0

x=np.array([40,20,40,90,2000,10])
print(x)
np.argmax(x)


[  40   20   40   90 2000   10]


np.int64(4)

In [52]:
# 28. Compare Two Arrays Element-Wise
# Write a NumPy program to compare two arrays using NumPy.
# Array a: [1 2]
# Array b: [4 5]
# a > b
# [False False]
# a >= b
# [False False]
# a < b
# [ True True]
# a <= b
# [ True True]

x=np.array([4,6,10,100,0])
y=np.array([2,3,9,90,120])
np.greater(x,y)

array([ True,  True,  True,  True, False])

In [61]:
# 29. Sort Array Along Axes
# Write a NumPy program to sort along the first and last axes of an array. Scripting Languages
# Sample array: [[2,5],[4,4]]
# Expected Output:
# Original array:
# [[4 6]
# [2 1]]
# Sort along the first axis:
# [[2 1]
# [4 6]]
# Sort along the last axis:
# [[1 2]
# [4 6]]

x=np.array([
    [10,20,15,5],
    [5,10,15,20],
    [-10,-5,0,9],
])
np.sort(x,axis=0)

array([[-10,  -5,   0,   5],
       [  5,  10,  15,   9],
       [ 10,  20,  15,  20]])

In [64]:
# 30. Sort Pairs by Names
# Write a NumPy program to sort pairs of a first name and a last name and return their indices (first by last name, then by first name).
# first_names = (Betsey, Shelley, Lanell, Genesis, Margery)
# last_names = (Battle, Brien, Plotner, Stahl, Woolum)
# Expected Output:
# [1 3 2 4 0]

x=np.array(['Betsey','Shelley','Lanell','Genesis','Margery'])
y=np.array(['Battle','Brien','Plotner','Stahl','Woolum'])
np.lexsort((x,y))

array([0, 1, 2, 3, 4])

In [77]:
# 31. Elements >10 & Their Indices
# Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.
# Original array:
# [[ 0 10 20]
# [20 30 40]]
# Values bigger than 10 = [20 20 30 40]
# Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

x=np.array([
    
    [0,10,20],   
    [20,30,40]
    
           ])
x>15
np.nonzero(x)

(array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))

In [79]:
# 32. Save Array to Text File

# Write a NumPy program to save a NumPy array to a text file.

x=np.array([[1,0],[1,0]])
np.savetxt('file.numpy',x)

In [81]:
# 33. Memory Size of Array

# Write a NumPy program to find the memory size of a NumPy array.

# Expected Output:

# 128 bytes
x.itemsize
x.size


4

In [90]:
# 34. Create Zeros and Ones Array
# Write a NumPy program to create an array of ones and zeros.
# Expected Output:

# Create an array of zeros
# Default type is float
# [[ 0. 0.]]
# Type changes to int
# [[0 0]]
# Create an array of ones
# Default type is float
# [[ 1. 1.]]
# Type changes to int
# [[1 1]]
x=np.ones(shape=(3,3),dtype=np.float32)
x


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [99]:
# 35. Change Array Dimensions

# Write a NumPy program to change an array's dimension. Scripting Languages

# Expected Output:

# 6 rows and 0 columns
# (6,)

# (3, 3) -> 3 rows and 3 columns
# [[1 2 3]
# [4 5 6]
# [7 8 9]]

# Change array shape to (3, 3) -> 3 rows and 3 columns
# [[1 2 3]
# [4 5 6]
# [7 8 9]]

x=np.arange(0,9).reshape(3,3)
x.shape
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
# 36. Flatten Array

# Write a NumPy program to create a contiguous flattened array.

# Original array:

# [[10 20 30]
# [20 40 50]]

# New flattened array:
# [10 20 30 20 40 50]

x=np.arange(10,61,10).reshape(2,3)
y=np.ravel(x)
y

array([10, 20, 30, 40, 50, 60])

In [122]:
x=x.reshape(-1,1)
x.shape

(6, 1)

In [128]:
# 37. Create 2D Array & Print Shape/Type

# Write a NumPy program to create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements), 
#also print the shape, type and data type of the array.

# Expected Output:
# (2, 3)
# int32
x=np.arange(0,6,dtype=np.int8).reshape(2,3)
print(f'the shape if {x.shape} and type is {type(x)} and {x.dtype}')

the shape if (2, 3) and type is <class 'numpy.ndarray'> and int8


In [130]:
# 38. Reshape Array (Keep Data)
# Write a NumPy program to create another shape from an array without changing its data.
# Reshape 3x2:
# [[1 2]
# [3 4]
# [5 6]]
# Reshape 2x3:
# [[1 2 3]
# [4 5 6]]

x=np.arange(0,6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [131]:
x.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [136]:
# 39. Change Array Data Type
# Write a NumPy program to change an array's data type.
# Expected Output:
# [[ 2 4 6]
# [ 6 8 10]]
# Data type of the array x is: int32
# New Type: float64
# [[ 2. 4. 6.]
# [ 6. 8. 10.]]

x.dtype
y=x.astype(float)
y.dtype

dtype('float64')

In [138]:
# 40. 3x5 Array Filled with 2s

# Write a NumPy program to create a new array of 3*5, filled with 2.

# Expected Output:

# [[2 2 2 2 2]
# [2 2 2 2 2]
# [2 2 2 2 2]]
# [[2 2 2 2 2]
# [2 2 2 2 2]
# [2 2 2 2 2]]

x=np.ones((5,5),dtype=np.int8)*2
x

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]], dtype=int8)

In [140]:
# 41. Array of 10s with Given Shape

# Write a NumPy program to create an array of 10's with the same shape and type as the given array. Scripting Languages
# Sample array: x = np.arange(4, dtype=np.int64)
# Expected Output:
# [10 10 10 10]

x = np.arange(4, dtype=np.int64)

# Creating a new array 'y' with the same shape and type as array 'x' but filled with the value 10 using full_like method
y = np.full_like(x, 10)
y

array([10, 10, 10, 10])

In [141]:
# 42. 3D Array with Diagonal Ones

# Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.

# Expected Output:

# [[ 1. 0. 0.]
# [ 0. 1. 0.]
# [ 0. 0. 1.]]

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [145]:
# 43. 2D Array with Custom Diagonal Values
# Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.
# Expected Output:
# [[4 0 0 0]
# [0 5 0 0]
# [0 0 6 0]
# [0 0 0 8]]
a=np.array([4,5,6,8])
x=np.diagflat(a)
x

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [152]:
# 44. 1D Array (0?50) & (10?50)
# Write a NumPy program to create a 1-D array with values from 0 to 50 and an array from 10 to 50.
# Expected Output:
# Array from 0 to 50:

# [ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
# 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
# Array from 10 to 50:
# [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
# 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

x=np.arange(0,51)
y=np.arange(10,51)
print(f'x is: {x} and \n]n y: {y}')

x is: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50] and 
]n y: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [154]:
# 45. 30 Evenly Spaced Values (2.5?6.5)

# Write a NumPy program to create a 1-D array of 30 evenly spaced elements between 2.5 and 6.5, inclusive.

# Expected Output:

# [ 2.5 2.63793103 2.77586207 2.9137931 3.05172414 3.18965517
# .................
# 5.81034483 5.94827586 6.0862069 6.22413793 6.36206897 6.5 ]

x=np.linspace(2.5,6.5,30)
x

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

In [157]:
# 46. 20 Log-Spaced Values (2?5)

# Write a NumPy program to create a 1-D array of 20 elements spaced evenly on a log scale between 2. and 5., exclusive.

# Expected Output:

# [ 100. 141.25375446 199.5262315 281.83829313
# ......................
# 25118.8643151 35481.33892336 50118.72336273 70794.57843841]

x=np.logspace(2,5,20,endpoint=False)
x

array([  100.        ,   141.25375446,   199.5262315 ,   281.83829313,
         398.10717055,   562.34132519,   794.32823472,  1122.0184543 ,
        1584.89319246,  2238.72113857,  3162.27766017,  4466.83592151,
        6309.5734448 ,  8912.50938134, 12589.25411794, 17782.79410039,
       25118.8643151 , 35481.33892336, 50118.72336273, 70794.57843841])

In [162]:
# 47. Create Zero/One Array Template

# Write a NumPy program to create an array like the one below.

# Expected Output:

# [[ 0. 0. 0.]
# ...........
# [ 1. 1. 1.]]

x=np.tri(4,4,)
x

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [164]:
# 48. Create 2D Array with Specific Values
# Write a NumPy program to create an array like the one below.Scripting Languages
# Expected Output:

# [[ 2 3 4]
# [ 5 6 7]
# [ 0 9 10]
# [ 0 0 13]]

x = np.triu(np.arange(2, 14).reshape(4, 3), -1)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 0,  9, 10],
       [ 0,  0, 13]])

In [175]:
# 49. Collapse 3D Array to 1D
# Write a NumPy program to collapse a 3-D array into a one-dimensional array.
# Expected Output:

# 3-D array:
# [[ 1. 0. 0.]
# [ 0. 1. 0.]
# [ 0. 0. 1.]]

# One dimension array:
# [ 1. 0. 0. 0. 1. 0. 0. 0. 1.]

a=np.eye(3)
a=np.ravel(a)
a.shape

(9,)

In [181]:
# 50. Find 4th Element of Array
# Write a NumPy program to find the 4th element of a specified array.
# Expected Output:

# [[ 2 4 6]
# [ 6 8 10]]
# Forth e1ement of the array:
# 6

a=np.array([[2,4,5],[6,8,10]])
print(a.flat[4])

8


In [183]:
# 51. Change Two Array Axes

# Write a NumPy program to change two array axes.

# Sample array: [[1 2 3]]

# Expected Output:
# [[1]
# [2]
# [3]]

a=np.arange(0,4)
a.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
# 52. Move Array Axes to Alternate Positions

# Write a NumPy program to move array axes to alternate positions. Other axes remain in their original order.

# Expected Output:

# (3, 4, 2)
# (4, 2, 3)

import numpy as np

# Creating a NumPy array filled with zeros of shape (2, 3, 4)
x = np.zeros((2, 3, 4))

# Moving the axis at index 0 to the last position (-1)
# The shape of the array after moving the axis from index 0 to index -1
print(np.moveaxis(x, 0, -1).shape)

# Moving the axis at the last position (-1) to index 0
# The shape of the array after moving the axis from index -1 to index 0
print(np.moveaxis(x, -1, 0).shape) 

In [ ]:
# Move Axis to Desired Position

# Write a NumPy program to move the specified axis backwards, until it lies in a given position.

# Move the following 3rd array axes to first position.
# (2,3,4,5)

# Sample Expected Output:
# (2, 5, 3, 4)

import numpy as np

# Creating a NumPy array filled with ones of shape (2, 3, 4, 5)
x = np.ones((2, 3, 4, 5))

# Using rollaxis to roll the axis at index 3 (last axis) to index 1
# Printing the shape of the array after rolling the axis from index 3 to index 1
print(np.rollaxis(x, 3, 1).shape) 

In [188]:
# 54. Inputs as Arrays with 1+ Dimensions

# Write a NumPy program to convert specified inputs into arrays with at least one dimension.

# Expected Output:

# [ 12.]
# [[ 0. 1. 2.]
# [ 3. 4. 5.]]

# [array([1]), array([3, 4])]

x = 12.0

# Ensuring that x is at least a 1-dimensional array
print(np.atleast_1d(x))

# Creating a NumPy array with shape (2, 3) using arange and reshape functions
x = np.arange(6.0).reshape(2, 3)

# # Ensuring that x is at least a 1-dimensional array
print(np.atleast_1d(x))

# # Attempting to convert 1 and [3, 4] into 1-dimensional arrays, which will raise an error
print(np.atleast_1d(1, [3, 4]))

[12.]
[[0. 1. 2.]
 [3. 4. 5.]]
(array([1]), array([3, 4]))


In [195]:
# 55. Inputs as Arrays with 2D/3D Views
# Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions. Scripting Languages
# Expected Output:

# View inputs as arrays with at least two dimensions:
# [10]
# [[ 0. 1.]
# [ 2. 3.]]

# View inputs as arrays with at least three dimensions:
# [[[15]]]
# [[[ 0.]
# [ 1.]
# [ 2.]]]
b=1
a=np.arange(6).reshape(2,3)
g=np.atleast_3d(a)
g.shape

(2, 3, 1)

In [200]:
# 56. Insert New Axis in 2D Array
# Write a NumPy program to insert a new axis within a 2-D array.
# 2-D array of shape (3, 4).
# Expected Output:
# New shape will be will be (3, 1, 4).

import numpy as np

# Creating a 3x4 array of zeros
x = np.zeros((3, 4))

# Expanding the dimensions of the array x along axis 1 and storing the shape of the result in y
y = np.expand_dims(x, axis=1).shape

# Printing the shape of the expanded array
print(y)

(3, 1, 4)


In [203]:
# 57. Remove Single-Dimensional Entries
# Write a NumPy program to remove single-dimensional entries from a specified shape.
# Specified shape: (3, 1, 4)
# Expected Output: (3, 4)

x = np.zeros((3, 1, 4))
x.squeeze().shape


(3, 4)

In [208]:
# 58. Concatenate 2D Arrays

# Write a NumPy program to concatenate two 2-dimensional arrays.
# Expected Output:
# Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
# Expected Output:
# [[ 0 1 3 0 2 4]
# [ 5 7 9 6 8 10]]

a=np.array([[0,1,3],[5,7,9]])
b=np.array([[0,2,4],[6,8,10]])
np.concatenate((a,b),axis=1).shape



(2, 6)

In [210]:
# 59. Convert 1D Arrays to 2D (as Columns)

# Write a NumPy program to convert 1-D arrays as columns into a 2-D array.

# Sample array: (10,20,30), (40,50,60)

# Expected Output:

# [[10 40]
# [20 50]
# [30 60]]

a=np.array([10,20,30])
b=np.array([40,50,60])
g=np.column_stack((a,b))
g

array([[10, 40],
       [20, 50],
       [30, 60]])

In [213]:
# 60. Depth-Wise Conversion of 1D to 2D
# Write a NumPy program to convert (in sequence depth wise (along the third axis)) two 1-D arrays into a 2-D array.

# Sample array: (10,20,30), (40,50,60)
# Expected Output:

# [[[10 40]]
# [[20 50]]
# [[30 60]]]
a=np.array([10,20,30])
b=np.array([40,50,60])
g=np.dstack((a,b))
g.shape


(1, 3, 2)

In [214]:
# 61. Split 14 Elements into 3 Arrays

# Write a NumPy program to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order.

# Expected Output:

# Original array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]

# After splitting:
# [array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

x=np.arange(15)
np.split(x,[2,6])

[array([0, 1]),
 array([2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])]

In [215]:
# 62. Split 4x4 Array Along Second Axis
# Write  a NumPy program that splits an array of shape 4x4 into two arrays along the second axis. Scripting Languages

# Sample array :
# [[ 0 1 2 3]
# ........
# [12 13 14 15]]

# Expected Output:
# [array([[ 0, 1],
# [ 4, 5],
# [ 8, 9],
# [12, 13]]),

# array([[ 2, 3],
# [ 6, 7],
# [10, 11],
# [14, 15]]), array([], shape=(4, 0), dtype=int64)]

# Creating a 4x4 NumPy array 'x' containing numbers from 0 to 15 using np.arange and reshape
x = np.arange(16).reshape((4, 4))

# Displaying the original 4x4 array 'x'
print("Original array:", x)

# Splitting the array 'x' horizontally into sub-arrays at columns 2 and 6 using np.hsplit
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))


Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]


In [219]:
# 63. Count Non-Zero Elements in Array

# Write a NumPy program to get the number of non-zero elements in an array.

# Expected Output:

# Original array:
# [[ 0 10 20]
# [20 30 40]]
import numpy as np
# Number of non zero elements in the above array:
# 5

x=np.array([0,0,0,1,1,1,0,0])
np.count_nonzero(x)

np.int64(3)

In [223]:
# 64. 5x5 Matrix with Row Values 0?4

# Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.

# Original array:
# [[ 0. 0. 0. 0. 0.]
# .........
# [ 0. 0. 0. 0. 0.]]

# Row values ranging from 0 to 4.
# [[ 0. 1. 2. 3. 4.]
# ..........
# [ 0. 1. 2. 3. 4.]]

x=np.zeros((5,5))
x=x+np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [233]:
# 65. Check Values Present in Array
# Write a NumPy program to test whether specified values are present in an array.
# Expected Output:

# Original array:
# [[ 1.12 2. 3.45]
# [ 2.33 5.12 6. ]]

# True
# False
# True
# False
# True

x=np.array([1.12, 2, 3.45, 2.33, 5.12,6]).reshape(2,-1)
print(2 in x)
print(3 in x)

True
False


In [235]:
# 66. Vector of Size 10 (0?1 Excluded)

# Write a NumPy program to create a vector of size 10 with values ranging from 0 to 1, both excluded.

# Expected Output:

# [ 0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
# 0.63636364 0.72727273 0.81818182 0.90909091]

x=np.linspace(0,1,10,endpoint=False)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
# 67. Make Array Read-Only

# Write a NumPy program to make an array immutable (read-only). Scripting Languages

# Expected Output:

# Test the array is read-only or not:
# Try to change the value of the first element:
# Traceback (most recent call last):

# File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
# x[0] = 1

# ValueError: assignment destination is read-only

x = np.zeros(10)

# Setting the 'writeable' flag of the array 'x' to False, making it read-only
x.flags.writeable = False

# Printing a message to test whether the array is read-only or not
print("Test the array is read-only or not:")

# Attempting to change the value of the first element in the array 'x'
print("Try to change the value of the first element:")
x[0] = 1  # This line will raise an error since the array is read-only 

In [254]:
# 68. Sum Multiples of 3 or 5 Below 100

# Write a NumPy program (using numpy) to sum all the multiples of 3 or 5 below 100.

# Expected Output:
# [ 3 5 6 9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51 54
# 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
# 2318
x=np.arange(1,100)
n=x[(x%3==0)  | (x%5==0)]
np.sum(n)

np.int64(2318)

In [256]:
# 69. Create Array with 10^3 Elements

# Write a NumPy program to create an array with 10^3 elements.

# Expected Output:

# [ 0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 10. 11.
# 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.
# 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
# - - - - - - - - - - - - - - - - -
# 972. 973. 974. 975. 976. 977. 978. 979. 980. 981. 982. 983.
# 984. 985. 986. 987. 988. 989. 990. 991. 992. 993. 994. 995.
# 996. 997. 998. 999.]

x=np.arange(0,1000).reshape(1,-1)
x

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [260]:
# 70. Display Every Array Element

# Write a NumPy program to create and display every element of a NumPy array.

# Expected Output:

# 0 1 2 3 4 5 6 7 8 9 10 11

x=np.arange(12)
for i in np.nditer(x):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [ ]:
# 71. Display Array Elements in Fortran Order

# Write a NumPy program to create and display every element of a NumPy array in Fortran order.

# Expected Output:

# Elements of the array in Fortan array:
# 0 4 8 1 5 9 2 6 10 3 7 11

